---
name: google-contacts
version: '0.0.0'
synopsis: Minimal Google Contacts API client
description: See https://github.com/pbrisbin/google-contacts#readme
category: Network
author: Pat Brisbin <pbrisbin@gmail.com>
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT
github: pbrisbin/google-contacts

dependencies:
  - base >=4 && <5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - google-oauth2 >= 0.3.0.0
    - http-conduit
    - safe-exceptions
    - directory
    - filepath
    - google-oauth2
    - hoauth2
    - text
    - xdg-basedir

executables:
  gc-config:
    main: Main.hs
    source-dirs: gc-config
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - google-contacts
  gc-mutt-query:
    main: Main.hs
    source-dirs: gc-mutt-query
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - google-contacts
      - optparse-applicative
      - text

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - bytestring
      - google-contacts
      - hspec
